# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Category

# Model Form Field configuration
form: $/meloncart/shop/models/category/fields.yaml

# Model Class name
modelClass: MelonCart\Shop\Models\Category

# Default redirect location
defaultRedirect: meloncart/shop/categories

# Create page
create:
    title: Create Categories
    redirect: meloncart/shop/categories/update/:id
    redirectClose: meloncart/shop/categories

# Update page
update:
    title: Edit Categories
    redirect: meloncart/shop/categories
    redirectClose: meloncart/shop/categories

# Preview page
preview:
    title: Preview Categories
