# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Order

# Model Form Field configuration
form: $/meloncart/shop/models/order/fields.yaml

# Model Class name
modelClass: MelonCart\Shop\Models\Order

# Default redirect location
defaultRedirect: meloncart/shop/orders

# Create page
create:
    title: Create Orders
    redirect: meloncart/shop/orders/update/:id
    redirectClose: meloncart/shop/orders

# Update page
update:
    title: Edit Orders
    redirect: meloncart/shop/orders
    redirectClose: meloncart/shop/orders

# Preview page
preview:
    title: Preview Orders
